version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - bookie-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-bookie:
    image: postgres:17
    container_name: db-bookie
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - bookie-network

  bookie-api:
    image: nogah1/bookie:latest
    container_name: bookie-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-bookie:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      SPRING_RABBITMQ_HOST: rabbitmq-broker
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS}

      MY_SECRET_KEY: ${JWT_SECRET}
    depends_on:
      rabbitmq:
        condition: service_healthy
      db-bookie:
        condition: service_started
    networks:
      - bookie-network

  timeline-service:
    image: nogah1/bookie-timeline:latest
    container_name: timeline-service
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_RABBITMQ_HOST: rabbitmq-broker
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
    depends_on:
      rabbitmq:
        condition: service_healthy
      db-bookie:
        condition: service_started
    networks:
      - bookie-network

networks:
  bookie-network:
    driver: bridge