name: Test and build Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Downloading code (checkout)
        uses: actions/checkout@v4

      - name: Configuring java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Compile and run tests
        run: mvn clean package

      - name: Upload de artefato (jar)
        uses: actions/upload-artifact@v4
        with:
          name: 'bookie-api-final'
          path: target/*.jar
          retention-days: 1