name: Test and build Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Downloading code (checkout)
        uses: actions/checkout@v4

      - name: Configuring java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Grant execute permissions
        run: chmod -x mvnw

      - name: Build with maven
        run: ./mvnw clean verify

      - name: Artifact upload (jar)
        uses: actions/upload-artifact@v4
        with:
          name: bookie-api-artifact
          path: target/*.jar